/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.mp.client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintStream;
import java.net.UnknownHostException;
import javafx.application.Application;


public class Client{
  final TextPlayer theTextPlayer;

  /**
   * constructor
   */
  public Client(String servername, int port, BufferedReader inputReader, PrintStream out)
      throws IOException, UnknownHostException {
    this.theTextPlayer = new TextPlayer(servername, port, inputReader, out);
  }


  public TextPlayer getTheTextPlayer() {
    return theTextPlayer;
  }

  /**
     * Main program for Client/Player
     */
  public static void main(String[] args) throws InterruptedException {
    Application.launch(startpage.class, args);

    /*
    try {
      System.out.println("Welcome to our game!");
      int port = args.length > 0 ? Integer.parseInt(args[1]) : 8080;
      String servername = args.length > 1 ? args[0] : "127.0.0.1";

      BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
      Client theClient = new Client(servername, port, input, System.out);

      if (servername != "null") {
        theClient.theTextPlayer.initiateGame();

        theClient.theTextPlayer.playGame();

        theClient.theTextPlayer.connectionToMaster.socket.close();

      } else {
        // The map should be received from master
        // Here we are mocking receiving player's color and map from server
        String test_color = "Green";
        theClient.theTextPlayer.setIdentity(test_color);
        System.out.println("My player's color: " + test_color);
        ArrayList<String> players_colors = new ArrayList<String>(Arrays.asList("Green", "Blue"));

        //OwnerChecking<Character> ownerchecker = new OwnerChecking<Character>(null);
        //PathChecking<Character> pathchecker = new PathChecking<Character>(ownerchecker);

        V2Map<Character> mapFromServer = new V2Map<Character>(players_colors);
        theClient.theTextPlayer.updateMap(mapFromServer);
        theClient.theTextPlayer.printMap();
        theClient.theTextPlayer.takeTurn();
      }

    } catch (

    Exception e) {
      e.printStackTrace();
    }
     */
  }
}
